title: ""
email: emilien.jemelen@inria.fr
description: ""
baseurl: ""
url: "emilien-jemelen.github.io"
github_username: emilien-jemelen

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

name: A minimal home page
exclude:
  - tmp/
  - vendor/
  - Gemfile
  - Gemfile.lock

css:
  - assets/css/custom.css
